on:
  push:
    branches: ["master", "CI"]
  pull_request:
    branches: ["master", "CI"]

name: CI

jobs:
  all-passes:
    name: Check for successful CI build
    runs-on: ubuntu-latest
    needs:
      - fmt
    steps:
      - run: exit 0

  fmt:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Poetry setup
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Install dependencies
        run: poetry install
      - name: Run autopep8
        run: ./scripts/check_autopep8.sh
